name = "DTools"
uuid = "73c671f0-943d-4098-8a4c-9538cdb752bf"
authors = ["edu4r2d <eduardquimica@gmail.com> and contributors"]
version = "0.0.2"

[compat]
julia = "1.6.7"

[deps]
PDBTools = "e29189f1"
MolSimToolkit = "054db54f"
StaticArrays = "90137ffa-7385-5640-8e0f-231f21f5686e"
Plots = "91a5bcdd"
ProgressMeter = "92933f4c"
KernelDensity = "5ab0869b"  # Verifique o UUID correto se necessário

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
